import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :ast_ninja, AstNinjaWeb.Endpoint,
  http: [:inet6, port: System.get_env("PORT") || 4000],
  url: [scheme: "https", host: "ast.ninja", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: false,
  server: true

# Do not print debug messages in production
config :logger, level: :info

config :ast_ninja, AstNinjaWeb.Endpoint,
  secret_key_base: "vkkOYLinc31DEOGWbLtCO+m5k4SooAwQIIPMeMRAC+LffgsA6GZ05imKeXoXSEFz"
